name: borrow_manager
description: A new Flutter project for managing borrows.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  sqflite: ^2.3.0
  path: ^1.9.1
  provider: ^6.1.1
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.13
  shared_preferences: ^2.2.2
  uuid: ^4.5.3
  image_picker: ^1.2.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/add_client.png
    - assets/images/lend_borrow.png
    - assets/images/reminder.png
    - assets/images/client_list.png
